# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
                ('isBusy', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTown', models.BooleanField(default=True)),
                ('arrivalTime', models.DateTimeField(blank=True)),
                ('status', models.CharField(default='pending', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Zone'),
        ),
        migrations.AddField(
            model_name='request',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger'),
        ),
        migrations.AddField(
            model_name='driver',
            name='requests',
            field=models.ManyToManyField(blank=True, to='driver.Request'),
        ),
        migrations.AddField(
            model_name='driver',
            name='zones',
            field=models.ManyToManyField(blank=True, to='driver.Zone'),
        ),
    ]
