# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.ManyToManyField(to='driver.Driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='requests',
        ),
        migrations.AddField(
            model_name='driver',
            name='requests',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='zones',
        ),
        migrations.AddField(
            model_name='driver',
            name='zones',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='request',
            name='arrivalTime',
            field=models.DateTimeField(),
        ),
    ]
