# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20161105_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='zones',
        ),
        migrations.AddField(
            model_name='driver',
            name='zoneFrom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='zoneTo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
