# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='zoneFrom',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='zoneTo',
        ),
        migrations.AddField(
            model_name='driver',
            name='zones',
            field=models.ManyToManyField(null=True, to='driver.Zone'),
        ),
    ]
