# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerID', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
    ]
